baseurl = "https://blockchainengineer.dev.github.io"
title = "Mainroad"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "papermod"


[Author]
    name = "John Doe"
    bio = "John Doe's true identity is unknown. Maybe
        he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.png"